Repository JollyJolli/HacktoberWall, pull requests merged in 2024-09, with the labels that each got.

#3 Add my name to contributors.json And Addition of dark mode switch
  app.js
  contributors.json
  index.html
  style.css
Labels: enhancement, hacktoberfest

#13 Added a Halloween Easter Egg feature to the Website (#9)
  app.js
  halloween-impact-05.mp3
  index.html
  style.css
Labels: hacktoberfest

#24 added surprise button || added my name to contributors
  src/app.js
  src/contributors.json
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#26 Fetch loader
  src/app.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, HTML, CSS, JavaScript

#27 fix (#20) : Implement a Feedback Mechanism
  src/form.css
  src/form.html
  src/form.js
Labels: hacktoberfest, hacktoberfest-accepted, HTML, CSS, JavaScript

#31 Solved favicon issue
  src/contributors.json
  src/form.html
  src/img/favicon.ico
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted
