Repository JollyJolli/HacktoberWall, pull requests merged in 2024-10, with the labels that each got.

#33 Added my name(Aditya) to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted

#37 Add my name to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted

#36 fix(#34): Make a better description for the website!
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#35 issue#34 fixed
  src/form.css
Labels: hacktoberfest, hacktoberfest-accepted

#39 Contributor Added Swaroop
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#40 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#41 Update: Add simcodes to the contributor.json file
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#44 Add my name to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#43 Updated contributors.json with Shree Gowtham
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#45 Added my name into contributiors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#47 Added Rainbow mode to give psychedelic effect
  .vscode/settings.json
  src/app.js
  src/contributors.json
  src/style.css
Labels: hacktoberfest-accepted, HTML, CSS, JavaScript, hacktoberfest2024

#48 Aria labels, Alt text for images and tab key navigation added
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#51 add my Name in Contributor.json File
  src/contributors.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, HTML, CSS, JavaScript, hacktoberfest2024

#52 Style: update background images for dark and light modes
  src/dark.png
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#53 Updated Contributors list
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#54 on search of word 'hacktober', a mascot floats through the screen
  src/app.js
  src/contributors.json
  src/index.html
  src/mascot.webp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#55 added memory cache to avoid constant refetching
  src/app.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#56 Added my name to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#59 Auto sort names alphabatically
  src/app.js
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#62 Added my name in contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#60 Create the feedback button and style it with appropriate style.
  src/contributors.json
  src/form.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#65 Feat: Finding the bug and reslove it.
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024, URGENT

#66 Suffling the contributors name on reload
  src/app.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#67 fixed invalid path
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#70 - functional modal
  src/app.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#71 Added my name :)
  src/contributors.json
Labels: hacktoberfest, hacktoberfest2024

#74 fixed search bar and added styles to card cmp
  src/contributors.json
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#77 - Resolve a bug with the card color in dark mode
  src/app.js
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#78 Update contributors.json - Added name
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#79 brick wall background and some basic changes
  src/app.js
  src/contributors.json
  src/img/bgm.png
  src/img/brick_wall.jpg
  src/img/dark.png
  src/img/mascot.webp
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#82 Fix (#81) : added name as contributor
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#85 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#87 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#88 custom ghost like cursor added , favicon added
  src/contributors.json
  src/img/icons8-ghost-16.png
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#89 Added my name to HacktoberWall
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#91 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#92 Add my name to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#95 Added Sort Feature
  src/app.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#97 Contributor count
  src/app.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#96 Added my name in contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#98 Added my name to HacktoberWall
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#104 - Add contributors section
  src/contributor.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#105 - Fix an oversight concerning the Css of contributors-section
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#106 - Code cleaning in app.js and contributors.js
  src/app.js
  src/contributor.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#109 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#110 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#111 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#116 added fun facts to list,
  src/app.js
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#117 fixing-responsive-list
  src/contributor.js
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#119 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#118 fixing smoothing scroll
  src/app.js
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#121 Added my name to contributors
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#126 fix: Improved responsiveness of Search Bar
  src/contributors.json
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#125 Cookie banner
  src/cookies.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#123 - get the CSS out of the HTML file.
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#128 - fix an typo error in style.css
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#130 Name updated
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#131 Added my name to contributers
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#132 Added name to contributors
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#135 [Feat] Added routing for form page and improved the UI for #102
  src/contributors.json
  src/form.css
  src/form.html
  src/form.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#136 Added name to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#137 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#134 updated a few things check them out
  src/app.js
  src/form.css
  src/form.js
  src/index.html
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#139 Update Contributors List
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#140 Update contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#146 Added name to contributors.json
  src/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#153 fix: logo redirects to homepage
  src/form.html
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#154 chore: create halloween-bg
  src/img/halloween-bg.webp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#156 Added formatting to code files and some css improvements
  src/css/form.css
  src/css/form.min.css
  src/css/style.css
  src/css/style.min.css
  src/data/contributors.json
  src/form.html
  src/index.html
  src/js/app.js
  src/js/app.min.js
  src/js/contributor.js
  src/js/contributor.min.js
  src/js/cookies.js
  src/js/cookies.min.js
  src/js/form.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#164 Changed styles in sort-by menu
  src/css/style.min.css
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#165 Update contributors.json to add name
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#166 Update contributors.json to add name
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#170 fix : changes made in about us section #162
  src/css/style.css
  src/css/style.min.css
  src/data/contributors.json
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#176 Contributor added
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#171 Add to contributers.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#179 Added Modal for Hacktoberfest: "Hacktoberfest is Almost Ending" 🎃
  src/css/modal.css
  src/css/modal.min.css
  src/data/contributors.json
  src/index.html
  src/js/modal.js
  src/js/modal.min.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#168 Fixed navbar in mobile
  src/css/style.min.css
  src/index.html
  src/js/app.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#184 Showcasing the repo "HacktoberWall" Statistics in the readme.md file #178
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#185 Jayadarshinig0609 patch 2
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#188 added google analytics to the page
  src/data/contributors.json
  src/form.html
  src/index.html
  src/tos.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#189 Added name to contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#190 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#192 BUG: Button Color
  src/css/style.css
  src/css/style.min.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#193 Updated contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#194 [Fix] Update toggleButton CSS to align with other navbar elements
  src/css/form.css
  src/css/form.min.css
  src/css/style.css
  src/css/style.min.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#196 feat: add pizofreude to contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#195 Navbar styling issue in dark mode #180
  src/css/style.min.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#197 added name in contributors json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024, gssoc-ext

#201 Added My Name to The Mural
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#199 Added my name
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#203 TNT's name
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#200 Add Taylor Dean to contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#204 Added my name to the contributor list.
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#205 add my name to the contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#206 Contributer
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#209 Added contributor name
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#210 modified contributors.js by adding name
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#212 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#208 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#213 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#216 Fixed Buttons not working issue #198
  src/form.html
  src/index.html
  src/tos.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#214 Added my name to contributors
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#218 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#226 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#229 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#231 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024

#232 Update contributors.json
  src/data/contributors.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2024
